apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    # Remove Origin header in local environments as Quarkus denies access to API endpoints
    # when started in development mode and the origin is not "localhost"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
      {{- if eq .Values.devMode true }}
      proxy_set_header Origin "";
      {{- end }}
    {{- if ne .Values.serverTier "local" }}
    cert-manager.io/issuer: "letsencrypt-{{ .Values.serverTier }}"
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      {{- if eq .Values.serverTier "local" }}
      secretName: "cinco-cloud-local-cert-secret"
      {{- else }}
      secretName: "letsencrypt-secret-{{ .Values.serverTier }}"
      {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: main-service
                port:
                  name: main
          {{- if eq .Values.devMode true }}
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: main-service
                port:
                  name: main-frontend
          {{- end }}
