serverTier: local
imagePullPolicy: Never
devMode: true
createPersistentVolumes: true
ingress:
  host: cinco-cloud
  class: public
certManager:
  email: alexander.bainczyk@tu-dortmund.de
postgresql:
  primary:
    service:
      type: NodePort
    persistentVolumeClaimRetentionPolicy:
      enabled: true
minio:
  service:
    type: NodePort
  persistence:
    size: 3Gi
mailhog:
  enabled: true
  service:
    type: NodePort
