serverTier: production
imagePullPolicy: IfNotPresent
storageClassName: microk8s-hostpath
devMode: false
ingress:
  host: demo.cinco-cloud.k8s.ls-5.de
  class: public
certManager:
  email: alexander.bainczyk@tu-dortmund.de
postgresql:
  global:
    storageClass: microk8s-hostpath
minio:
  global:
    storageClass: microk8s-hostpath
archetype:
  storage: 2Gi
  hostPath: /mnt/data/demo/cinco-cloud/archetype
