# The name of the environment. Valid values are 'production' and 'local'.
serverTier: production

# If CincoCloud is started in debug mode. Should be 'false' if serverTier is 'production'.
debug: false

# Indicates that CincoCloud runs behind a ssl terminating reverse proxy, i.e., is reached by using https.
ssl: true

# The storage class name to use for persistent volumes.
storageClassName: standard

# The policy with which images are pulled. Should be 'Never' in local development mode and 'IfNotPresent' in production.
imagePullPolicy: IfNotPresent

# If persistent volumes are created by hand. 'false' if volumes are created automatically by claims. 
createPersistentVolumes: false

# The image of the main service.
mainImage: registry.gitlab.com/scce/cinco-cloud/main:latest

# Configuration for the ingress controller.
ingress:
  # The host where CincoCloud is deployed.
  host: app.example.com
  # The class for nginx.
  class: public

# Configuration for the cert manager.
certManager:
  # The email the certificates are issued to.
  email: demo@example.com

# Configuration for the main service.
main:
  mailer:
    ssl: false
    from: cincocloud@example.com

# Configuration for the postgres database.
postgresql:
  global:
    storageClass: standard
    postgresql:
      auth:
        database: cc
        username: cc
        existingSecret: cinco-cloud-main-secrets
        secretKeys:
          adminPasswordKey: postgresAdminPassword
          userPasswordKey: postgresUserPassword
  primary:
    persistence:
      storageClass: standard
      size: 10Gi

# Configuration for the minio object storage.
minio:
  mode: distributed
  statefulset:
    replicaCount: 2
    drivesPerNode: 2
  global:
    storageClass: standard
  auth:
    existingSecret: cinco-cloud-main-secrets
  persistence:
    size: 10Gi

# Configuration for mailhog
mailhog:
  enabled: false
  containerPort:
    smtp:
      port: 1025

# Configuration for the archetype image and Theia editors.
archetype:
  # The image that is used for editors.
  image:
  # The amount of available storage.
  storage: 2Gi
  # The path on the host machine where files are stored
  hostPath: /mnt/data/cincocloud/archetype
