name: Release Cinco Cloud Chart
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.repository }}
      CHART_PATH: ./charts/cinco-cloud
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 5

      - name: Configure Git
        run: |
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add Helm repositories for dependencies
        run: |
            helm repo add bitnami https://charts.bitnami.com/bitnami
            helm repo add codecentric https://codecentric.github.io/helm-charts

      - name: Run chart-releaser    
        uses: helm/chart-releaser-action@v1.6.0
        env:
         CR_TOKEN: "${{ secrets.ACCESS_TOKEN }}"